CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(128) NOT NULL,
    email VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    cargo VARCHAR(20) NOT NULL,
    CONSTRAINT pk_usuarios PRIMARY KEY (id),
    CONSTRAINT uq_usuarios_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS servicos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(128) NOT NULL,
    valor DECIMAL(10, 2) NOT NULL,
    duracao INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    CONSTRAINT pk_servicos PRIMARY KEY (id),
    CONSTRAINT uq_servicos_nome UNIQUE (nome)
);

CREATE TABLE IF NOT EXISTS disponibilidades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    dia_semana VARCHAR(10) NOT NULL,
    hora_inicio TIME NOT NULL,
    hora_fim TIME NOT NULL,
    CONSTRAINT pk_disponibilidades PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS agendamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    data TIMESTAMP NOT NULL,
    duracao INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    usuario_id BIGINT NOT NULL,
    servico_id BIGINT NOT NULL,
    CONSTRAINT pk_agendamentos PRIMARY KEY (id),
    CONSTRAINT fk_agendamentos_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id),
    CONSTRAINT fk_agendamentos_servico FOREIGN KEY (servico_id) REFERENCES servicos (id)
);
